export interface UsStateTerritory {
  abbrev: string;
  name: string;
}

export const UsStatesTerritories = [
  { abbrev: "AK", name: "Alaska" },
  { abbrev: "AL", name: "Alabama" },
  { abbrev: "AR", name: "Arkansas" },
  { abbrev: "AS", name: "American Samoa" },
  { abbrev: "AZ", name: "Arizona" },
  { abbrev: "CA", name: "California" },
  { abbrev: "CO", name: "Colorado" },
  { abbrev: "CT", name: "Connecticut" },
  { abbrev: "DC", name: "District Of Columbia" },
  { abbrev: "DE", name: "Delaware" },
  { abbrev: "FL", name: "Florida" },
  { abbrev: "GA", name: "Georgia" },
  { abbrev: "GU", name: "Guam" },
  { abbrev: "HI", name: "Hawaii" },
  { abbrev: "IA", name: "Iowa" },
  { abbrev: "ID", name: "Idaho" },
  { abbrev: "IL", name: "Illinois" },
  { abbrev: "IN", name: "Indiana" },
  { abbrev: "KS", name: "Kansas" },
  { abbrev: "KY", name: "Kentucky" },
  { abbrev: "LA", name: "Louisiana" },
  { abbrev: "MA", name: "Massachusetts" },
  { abbrev: "MD", name: "Maryland" },
  { abbrev: "ME", name: "Maine" },
  { abbrev: "MI", name: "Michigan" },
  { abbrev: "MN", name: "Minnesota" },
  { abbrev: "MO", name: "Missouri" },
  { abbrev: "MP", name: "Northern Mariana Islands" },
  { abbrev: "MS", name: "Mississippi" },
  { abbrev: "MT", name: "Montana" },
  { abbrev: "NC", name: "North Carolina" },
  { abbrev: "ND", name: "North Dakota" },
  { abbrev: "NE", name: "Nebraska" },
  { abbrev: "NH", name: "New Hampshire" },
  { abbrev: "NJ", name: "New Jersey" },
  { abbrev: "NM", name: "New Mexico" },
  { abbrev: "NV", name: "Nevada" },
  { abbrev: "NY", name: "New York" },
  { abbrev: "OH", name: "Ohio" },
  { abbrev: "OK", name: "Oklahoma" },
  { abbrev: "OR", name: "Oregon" },
  { abbrev: "PA", name: "Pennsylvania" },
  { abbrev: "PR", name: "Puerto Rico" },
  { abbrev: "RI", name: "Rhode Island" },
  { abbrev: "SC", name: "South Carolina" },
  { abbrev: "SD", name: "South Dakota" },
  { abbrev: "TN", name: "Tennessee" },
  { abbrev: "TX", name: "Texas" },
  { abbrev: "UT", name: "Utah" },
  { abbrev: "VA", name: "Virginia" },
  { abbrev: "VI", name: "Virgin Islands" },
  { abbrev: "VT", name: "Vermont" },
  { abbrev: "WA", name: "Washington" },
  { abbrev: "WI", name: "Wisconsin" },
  { abbrev: "WV", name: "West Virginia" },
  { abbrev: "WY", name: "Wyoming" }
];
